FROM python:3.8-slim
RUN mkdir /app
COPY requirements.txt /app
RUN pip3 install --upgrade pip
RUN pip3 install -r /app/requirements.txt --no-cache-dir
COPY . /app
WORKDIR /app
CMD ["gunicorn", "placeremember.wsgi:application", "--bind", "0:8000"]
