# Generated by Django 4.0.5 on 2022-06-06 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Impression title')),
                ('content', models.TextField(verbose_name='Твои впечатления')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date of creation')),
                ('date_changed', models.DateTimeField(auto_now=True, verbose_name='Date of change')),
                ('address', models.CharField(max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63, verbose_name='Координаты')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Impression',
                'verbose_name_plural': 'Impressions',
            },
        ),
    ]
